### ISSUE TITLE
question: how to go to the home page

### ISSUE THREAD

**Issue by tusharnankani** [dheerajdlalwani/back-to-work#3]
Once the extension is unpacked and loaded, I get the home page.

But how do I get back there again? 

![image](https://user-images.githubusercontent.com/61280281/149566326-67ec7447-d078-4a6f-9256-18fb7ce767ad.png)

Right now, when I reload the extension, I get the homepage:

![image](https://user-images.githubusercontent.com/61280281/149566543-10a59860-7640-46d0-bd8d-e2513a00d56c.png)

**Comment by dheerajdlalwani** [comment]
> Once the extension is unpacked and loaded, I get the home page.

So basically, that page which you see is not the home page. Home page is yet to be implemented, which will also double up as an onboarding page for the users.

---

> But how do I get back there again?

Oh that's a great question, Tushar.
The page which you see is known as the options page, which let's the user customise the . It can be accessed by right-clicking on the extension's icon & then choosing "Options" from the menu. (See image below 👇🏼)

![image](https://user-images.githubusercontent.com/52416311/149575979-a240a090-1c37-44b4-94a2-fb4ff9221c92.png)

Right now, I've kept the setting such that the options page opens automatically as soon as the extension is installed/reloaded.

**Comment by tusharnankani** [comment]
Thank you, that answers!
