### ISSUE TITLE
alt: clean JS, better implementation using classes  

### ISSUE THREAD

**Issue by tusharnankani** [dheerajdlalwani/back-to-work#5]
Review: The code here can be shortened by creating classes and defining styles in the stylesheet. 

https://github.com/dheerajdlalwani/back-to-work/blob/fc5c9820ee350dc1ab69f9c9aff77465bc33f979/src/popup/popup.js#L7-L18

It can be shortened more using a default, which I assume is `Chill`. Have the HTML, state & styles initially for that. 

Have a class for `Work`, and toggle that whenever necessary.

```javascript
 (mode === "Work") ? modeBtn.classList.add("work") : modeBtn.classList.remove("work");
```

Now CSS for work would be something like:
```css
.work {
  content: "work";
  background-color: #f95050;
  color: #ffffff;
}
```

Reason to do that? 

Keeps the JS clean and and implementation short. No need for `item.style.backgroundColor` etc.

**Comment by dheerajdlalwani** [comment]
- Ahh, this suggestion helped me clean up my code quite a bit!
- Thank you so much for raising this issue 😄
