### ISSUE TITLE
enhancement: Detailed status of the modes.

### ISSUE THREAD

**Issue by varunmamtora06** [dheerajdlalwani/back-to-work#6]
## Current ui
1. When `chill mode` is on, it says `chill`:
![image](https://user-images.githubusercontent.com/58453023/149613018-cfefea30-080c-41f6-a3bf-898d1a52fbb2.png)
2. When `work mode` is on, it says `work`:
![image](https://user-images.githubusercontent.com/58453023/149613028-0cfcb9c4-cfe0-43a7-8902-cc81e910f696.png)

## Enchancement
While in `chill mode`, the status text shall say `chilling...` and on hovering over that it should say `work` or maybe `switch to work`  clicking upon which shall switch to `work mode` and status text should say `working...` vice versa.

Check the clip below.

https://user-images.githubusercontent.com/58453023/149613234-b5617bdc-d222-41a0-9ca7-0766a68a5ae8.mp4

**Comment by dheerajdlalwani** [comment]
That's a very good suggestion, @varunmamtora06 .
Infact, at this point, it's not even enhancement, it's necessary. But yeah, I do have some UI/UX plans for addressing this. Shall update here later. 
Thank you for raising this issue!

**Comment by dheerajdlalwani** [comment]
Completely revamped the UI for the popup.

![image](https://user-images.githubusercontent.com/52416311/150732297-5f90456a-5074-4966-b91b-8ed239823e50.png)
![image](https://user-images.githubusercontent.com/52416311/150732331-30de546e-7e0a-4a42-9fbb-9ce62d3cb746.png)

Feel like it significantly improves the UX.

Thank you for raising this issue 😄
